delete_cluster_after_execution: false
overwrite_tasks: true  # overwrite tasks with the same tag?
tasks:
  # ================================ EXP 1 ================================
  - task_tag: "exp 1-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 1-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 1-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 1-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 1-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp1-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp1-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 2 ================================
  - task_tag: "exp 2-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 2-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 2-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 2-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 2-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp2-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp2-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 3 ================================
  - task_tag: "exp 3-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 3-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 3-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 3-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 3-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp3-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp3-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================
