delete_cluster_after_execution: false
overwrite_tasks: true  # overwrite tasks with the same tag?
tasks:
  # ================================ EXP 13 ================================
  - task_tag: "exp 13-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 13-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 13-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 13-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 13-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp13-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp13-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 14 ================================
  - task_tag: "exp 14-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 14-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 14-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 14-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 14-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp14-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp14-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 15 ================================
  - task_tag: "exp 15-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 15-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 15-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 15-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 15-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 32 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 16 -q 16 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp15-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp15-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================
