delete_cluster_after_execution: false
overwrite_tasks: true  # overwrite tasks with the same tag?
tasks:
  # ================================ EXP 22 ================================
  - task_tag: "exp 22-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 22-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 22-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 22-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 22-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp22-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp22-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 23 ================================
  - task_tag: "exp 23-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 23-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 23-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 23-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 23-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp23-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp23-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 24 ================================
  - task_tag: "exp 24-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 24-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 24-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 24-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 24-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp24-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp24-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================
