delete_cluster_after_execution: false
overwrite_tasks: true  # overwrite tasks with the same tag?
tasks:
  # ================================ EXP 10 ================================
  - task_tag: "exp 10-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 10-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 10-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 10-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 10-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-partner .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp10-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp10-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 11 ================================
  - task_tag: "exp 11-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 11-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 11-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 11-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 11-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-xor .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp11-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp11-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================

  # ================================ EXP 12 ================================
  - task_tag: "exp 12-1"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-1.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-1.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-1.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 12-2"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-2.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-2.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-2.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 12-3"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-3.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-3.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-3.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 12-4"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-4.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-4.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-4.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs

  - task_tag: "exp 12-5"
    fault_tolerance_technology_label: "SCR"
    checkpoint_strategy_label: "SCR"
    setup_command: "cd /var/nfs_dir/my_files/jacobi-method && make jacobi_scr && rm .scrconf && cp .scrconf-rs .scrconf"
    run_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-5.txt
      "
    ckpt_command: null
    restart_command: "
      cd /var/nfs_dir/my_files/jacobi-method/ &&
      mpirun -np 64 -hostfile /var/nfs_dir/my_files/hostfile jacobi_scr -p 32 -q 32 -NB 2048 --debug
      | tail -n 13 >> /var/nfs_dir/my_files/outputs/exp12-5.txt && echo >> /var/nfs_dir/my_files/outputs/exp12-5.txt
      "
    retries_before_aborting: 3  # maximum number of retries before aborting execution
    remote_outputs_dir: /var/nfs_dir/my_files/outputs
  # =======================================================================
